FROM postgres:17-alpine

# Set Environment Variables
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD nekolab2025

# Install Dependencies
RUN apk update && apk upgrade
RUN apk add --no-cache dcron

# Setup Configuration
COPY backup.sh /usr/local/bin/backup.sh
COPY crontab_jobs /etc/crontabs/root
COPY service_init.sh /usr/local/bin/service_init.sh
COPY init.sql /docker-entrypoint-initdb.d/init.sql
RUN chmod 700 /usr/local/bin/backup.sh
RUN chmod 600 /etc/crontabs/root
RUN chmod +x /usr/local/bin/service_init.sh
RUN touch /var/log/cron.log
RUN ls -l /usr/local/bin/

EXPOSE 5432

# Startup Command
CMD ["/usr/local/bin/service_init.sh"]
